language: r
dist: xenial
latex: false

branches:
  only:
    - master

cache:
  packages: yes
  directories:
    - $HOME/bin

script:
  - Rscript -e 'rmarkdown::render_site()'

deploy:
  provider: pages
  repo: ecofw/ecofw.github.io   
  on:
    branch: master
  local_dir: _site
  skip_cleanup: true

### Adapted from https://bookdown.org/yihui/blogdown/travis-github.html
