---
title: "Hawai‘i CSA Resource Webtool"
---

Agricultural practices are a key adaptation for both addressing
contributing factors to climate change and mitigating
impacts. Resources for supporting current activities and transitions
to CSA practices are increasingly available from multiple sources. The
Hawai‘i CSA Resource Webtool provides a way to more effectively
navigate these resources.

# Using the Interface

Our team has compiled a database of CSA resources that can be accessed
at
[https://uhwo.shinyapps.io/hicsatool](https://uhwo.shinyapps.io/hicsatool). To
use the tool: 

- Select the CSA practices of interest. 
- Read about and follow the links to the resources. 
- Information for the selected practices can be exported by clicking
  on the `Download Selected Rows` button. 
- At any time, the entire list of practices can cleared via the
  `Deselect All` button and re-selected by refreshing the webpage. 

# More information:

- Please submit feature requests and bugs to the
  [issues](https://forms.gle/eRzdRQ3W6NRcDQGA6) system.
- More details of the database project, including the data pipeline
  for  can be found in
  [hi-csa-db.pdf](https://github.com/ecoFw/hi-csa-db/blob/9a50b0bf0bb518dd775fa189e8a691efa9275b18/hi-csa-db.pdf "hi-csa-db.pdf").
- Contact Dr. Matthew Kekoa Lau [mklau3@hawaii.edu](mklau3@hawaii.edu
  "mklau3@hawaii.edu") for further questions about the project.


# Project Funding and Support

This project is supported by a grant from the City and County of
Honolulu Office of Climate Change, Sustainability and Resilience
([https://www.resilientoahu.org/](https://www.resilientoahu.org/)). Development is made possible by
the following team of collaborators:

Dr. Matthew Kekoa Lau, UH West O‘ahu (co-lead) \
Lucas McKinnon, Hawai‘i Good Food Alliance (co-lead) \
Jackson Hart, Pacific Gateway Center  \
Jason Shawn, Honolulu City and County \
Amanda Shaw, O‘ahu Agriculture and Conservation Association (OACA) \



-------------------------------------------------------------------------------
