---
title: agri-urban dynamics
author: MK Lau
date: '2018-06-29'
slug: agri-urban-dynamics
categories: []
tags: [foodways]
description: ''
featured: ''
featuredalt: ''
featuredpath: ''
linktitle: ''
---

# The connection of urban evolution to shifting foodways

Topics:

- The Green Revolution: decline in labor demand and consolidation of
  farmlands lead to migration of farm workers to urban centers
  and character of cities at different scales
- The Civil War and Pacific Imperialism: the fight over slavery driven
  practices of the south lead to a transition of plantation
  agrictulture in the south pacific islands controlled by US
  interests
- American colonial land aquisition: disenfranchisement of First
  Peoples of the Americas were strongly dictated by perspectives on
  food and land-use, with Spanish, British, French and Dutch, and
  eventually United States, interests dominating.
  

# Questions: 

- How did shfiting agricultural practices, particularly food related,
influence the the growth and characteristics of cities?
- Is there evidence for periodic shifts (e.g. Tipping Points of
  urban-suburban midwest US) propelling urban growth?
- Are there contemporary mechanisms and/or patterns today?


## From "The Hawaiian Kingdom vol 3 1874-1893, The Kalakaua Dynasty" by R.S. Keykendall

- The "Reciprocity Treaty" solidified sugar as a dominant agriculture
  of the Hawaiian Islands
- "The long-range effect of the reciprocity treaty was to magnify the
  relative importance of the sugar industry."
- "... the *Hawaiian Star Gazette* remarked (June 27, 1877): "It is
  apparent that Sugar is destined most emphatically to be 'King'..."
- "The production of sugar was a complicated enterprise and, for best
  results, a costly one. Best results could only be obtained by
  large-scale plantation methods."
- "The large profits resulting from the cultivation of and manufacture
  of sugar, where inexpensive Asiatic labor was to be obtained,
  produced the legitimate result of aggregating capital in large
  amounts for the purchase or leasing of sugar lands..."


## Contemporary agri-urban dynamics: Mexican labor and transitioning U.S. cities

- Economic and political instability could be driving migrations from
  Central and Latin American countries to U.S. agriculture and cities
- How have major urban centers of the U.S. been experiencing migration
  waves: Los Angeles, San Francisco, Seattle, Phoenix, Houston,
  Austin, Dallas-Fort Worth, New Orleans, Minnieapolis-St. Paul,
  Atlanta, New York, Boston?
- This seems to be mirrored in Europe with migrations of workers from Africa
